name: CI-CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/course-app:${{ steps.vars.outputs.sha_short }}, ${{ secrets.DOCKERHUB_USERNAME }}/course-app:latest
          
      - name: Update Kubernetes Manifest
        run: |
          # Cài đặt Kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

          # Đi vào thư mục k8s
          cd k8s

          # Sử dụng Kustomize để đặt image tag mới
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/course-app:${{ steps.vars.outputs.sha_short }}
          
          # Cấu hình Git
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          
          # Thêm file
          git add kustomization.yaml

          # --- PHẦN SỬA LỖI ĐÂY ---
          # Chỉ commit và push NẾU có thay đổi
          if git diff-index --quiet HEAD; then
            echo "Kustomization.yaml is already up to date. No commit needed."
          else
            echo "Changes detected, committing and pushing..."
            git commit -m "CI: Update image tag to ${{ steps.vars.outputs.sha_short }} [skip ci]"
            git push
          fi
